version: '2'
services:
  mysql:
    image: mysql
#    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=keepmesecret
      - MYSQL_USER=metacat
      - MYSQL_PASSWORD=metacat
      - MYSQL_DATABASE=metacat

  metastore:
    build: metastore
    ports:
      - "9083:9083"
    volumes:
      - "./catalog:/etc/catalog"
    environment:
      - MYSQL_USER=metacat
      - MYSQL_PASSWORD=metacat
      - MYSQL_DATABASE=metacat
      - MYSQL_HOST=mysql:3306

  metacat:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - "./catalog:/etc/catalog"
    environment:
      - MYSQL_USER=metacat
      - MYSQL_PASSWORD=metacat
      - MYSQL_DATABASE=metacat
      - MYSQL_HOST=mysql:3306
